# Generated by Django 3.0.3 on 2021-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_park', models.CharField(default=None, max_length=50, null=True)),
                ('bsk_number', models.IntegerField(default=None)),
                ('appeal_num', models.IntegerField(default=None)),
                ('appeal_create_date', models.DateField(default=None, null=True)),
                ('appeal_code', models.CharField(default=None, max_length=50, null=True)),
                ('appeal_method', models.CharField(default=None, max_length=50, null=True)),
                ('appeal_owner_name', models.CharField(default=None, max_length=50, null=True)),
                ('appeal_owner_phone_number', models.CharField(default=None, max_length=50, null=True)),
                ('district', models.CharField(default=None, max_length=50, null=True)),
                ('incident_date', models.DateField(default=None, null=True)),
                ('incident_time', models.DateField(default=None, null=True)),
                ('route_number', models.IntegerField(default=None, null=True)),
                ('stop_name', models.CharField(default=None, max_length=50, null=True)),
                ('route_direction', models.CharField(default=None, max_length=50, null=True)),
                ('auto_number', models.CharField(default=None, max_length=50, null=True)),
                ('answer_method', models.CharField(default=None, max_length=50, null=True)),
                ('answer', models.TextField(default=None, max_length=500, null=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
