# Generated by Django 3.0.3 on 2021-04-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_auto_20210401_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_num',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
