# Generated by Django 3.0.3 on 2021-04-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_auto_20210405_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAppeal',
            fields=[
                ('appeal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appeal.Appeal')),
            ],
            bases=('appeal.appeal',),
        ),
    ]
