# Generated by Django 3.0.3 on 2021-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0005_auto_20210413_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='archivated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArchiveAppeal',
        ),
    ]
